test

diff --git a/.github/workflows/benchmark.yml b/.github/workflows/benchmark.yml
--- a/.github/workflows/benchmark.yml
+++ b/.github/workflows/benchmark.yml
@@ -44,8 +44,8 @@ jobs:
 
       - name: Stop servers
         run: |
-          kill $(cat mock_server.pid)
-          kill $(cat main_server.pid)
+          cat mock_server.pid | xargs kill || echo "Failed to kill mock server process"
+          cat main_server.pid | xargs kill || echo "Failed to kill main server process"
 
       - name: Generate profile report
         run: |
